name: Urban_block_party
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  flutter_launcher_name: ^0.0.1


  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^2.0.0
  flutter_zoom_drawer:
    path: ../

  shared_preferences: ^2.0.15

  animated_splash_screen: ^1.3.0

  video_player: ^2.2.18
  cloud_firestore: ^3.4.2
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  fluttertoast: ^8.0.9
  google_sign_in: ^5.4.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  flutter_sticky_header: ^0.6.4
  dropdown_button2: ^1.8.0
  flutter_email_sender: ^5.1.0
  image_picker: ^0.8.5+3
  webview_flutter: ^3.0.4
  firebase_storage: ^10.3.6
  video_thumbnail: ^0.5.2
  file_picker: ^5.0.1
  path_provider: ^2.0.11
  page_transition: ^2.0.9
  floating_action_bubble: ^1.1.4
  url_launcher: ^6.1.5
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.2.0
  location: ^4.0.0
  avatar_glow: ^2.0.2
  getwidget: ^2.0.4
  money_formatter: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/videos/splash.mp4
    - assets/videos/test.mp4
    - assets/videos/splash_video.mp4
    - assets/images/logo.png
    - assets/images/home.png
    - assets/images/contact_icon.png
    - assets/images/camera_icon.png
    - assets/images/aboutus_icon.png
    - assets/images/loader_floating.flr
    - assets/images/bell.png
    - assets/images/CropODF3.png
    - assets/images/iosmarketing.png
    - assets/images/aboutus_img.png
    - assets/images/microphone.png
    - assets/images/help.png
    - assets/images/video.png
    - assets/images/ubpx-app-logo-200-clr.png
    - assets/images/background_login.jpg
